### ISSUE TITLE
Error with example

### ISSUE THREAD

**Issue by hsane2001** [jthomas/openwhisk-metrics#1]
Running the example in the readme after installing the openwhisk-metrics module gives me this error:

node_modules/openwhisk-metrics/index.js:13
  return async params => {
               ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by jthomas** [comment]
This package needs a Node.js 8 or above runtime. This is available in OpenWhisk but not the default Node.js runtime version. Use the `--kind` flag when creating your action to set the correct version.

```
wsk action create myAction myAction.js --kind nodejs:8
```

**Comment by hsane2001** [comment]
Thanks, Got past that but still get this error: 
"error": "Initialization has failed due to: Error: Cannot find module '/home/hsane/node_modules/openwhisk-metrics'\n    at Function.Module._resolveFilename (module.js:536:15)\n    at Function.Module._load (module.js:466:25)\n    at Module.require (module.js:579:17)\n    at require (internal/module.js:11:18)\n    at eval (eval at NodeActionRunner.init (/nodejsAction/runner.js:76:45), <anonymous>:1:29)\n    at eval (eval at NodeActionRunner.init (/nodejsAction/runner.js:76:45), <anonymous>:9:14)\n    at NodeActionRunner.init (/nodejsAction/runner.js:76:45)\n    at doInit (/nodejsAction/src/service.js:134:31)\n    at initCode (/nodejsAction/src/service.js:82:24)\n    at /nodejsAction/app.js:61:13"

How does the action find the openwhisk-metrics library? Do you have to install it within the container?

**Comment by jthomas** [comment]
This library will have to be bundled within the action deployment package. This blog post shows the steps needed to do this.
http://jamesthom.as/blog/2016/11/28/npm-modules-in-openwhisk/

**Comment by hsane2001** [comment]
Thanks jthomas - That seemed to work and I also learned how to zip actions and its dependencies together. Not sure if this process has more overhead for the framework to split files and execute at runtime. It may be helpful to call it out in your "usage" section, for not all users may be aware of this. Thanks again!
